FROM resin/%%RESIN_MACHINE_NAME%%-debian

MAINTAINER Gergely Imreh <gergely@resin.io>

ENV INITSYSTEM on

WORKDIR /usr/src/app

RUN echo debconf shared/accepted-wolfram-eula select true | debconf-set-selections && \
    apt-get update && \
    apt-get install -qy --no-install-recommends  \
      wolfram-engine \
    && apt-cache clean && rm -rf /var/lib/apt/lists

CMD while : ; do echo "Idling..."; sleep 60; done
